/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts;

/**
 *
 * @author adhary
 */
public class uts10120205 extends javax.swing.JFrame {

    /**
     * Creates new form uts10120205
     */
    public uts10120205() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbPahaAtas = new javax.swing.JCheckBox();
        cbPahaBawah = new javax.swing.JCheckBox();
        cbSayap = new javax.swing.JCheckBox();
        cbAti = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txtJumlahPahaAtas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbLangsung = new javax.swing.JRadioButton();
        rbPemesanan = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        txtJumlahPahaBawah = new javax.swing.JTextField();
        txtJumlahAti = new javax.swing.JTextField();
        txtJumlahSayap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Pembeli");

        jLabel2.setText("Jenis");

        cbPahaAtas.setText("Paha Atas");

        cbPahaBawah.setText("Paha Bawah");

        cbSayap.setText("Sayap");

        cbAti.setText("Ati Ampela");

        jLabel3.setText("Jumlah");

        jLabel4.setText("Jenis Pembelian");

        buttonGroup1.add(rbLangsung);
        rbLangsung.setText("Langsung");

        buttonGroup1.add(rbPemesanan);
        rbPemesanan.setText("Pemesanan");

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        jLabel5.setText("DIKERJAKAN OLEH");

        jLabel6.setText("NIM             : 10120205");

        jLabel7.setText("NAMA         : RAYA ADHARY");

        jLabel8.setText("SEMESTER : 4");

        jLabel9.setText("KELAS        : IF 5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbAti)
                                            .addComponent(cbSayap)
                                            .addComponent(cbPahaAtas)
                                            .addComponent(jLabel2))
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbPahaBawah)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(69, 69, 69))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtJumlahPahaBawah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJumlahSayap, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJumlahAti, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJumlahPahaAtas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(60, 60, 60))))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rbPemesanan)
                            .addComponent(rbLangsung))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbPahaAtas)
                                    .addComponent(txtJumlahPahaAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtJumlahPahaBawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbPahaBawah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJumlahSayap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSayap, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJumlahAti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAti))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbLangsung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPemesanan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // mendapatkan nama
        String nama = txtNama.getText();
        txtOutput.append("Nama Pembeli\t\t"+nama+"\n");
        
        // definisi variabel dan konstanta
        final int PahaAtas = 5000;
        final int PahaBawah = 4500;
        final int Sayap = 2500;
        final int Ati = 2000;
        int potongan = 0;
        int subtotal = 0;
        int biayaPesan;
        int pajak;
        int totalBayar;
        
        // checkbox pilihan menu
        
        if (cbPahaAtas.isSelected())
        {
            int jumlah = Integer.parseInt(txtJumlahPahaAtas.getText());
          
            int harga = PahaAtas * jumlah;
            subtotal += harga;
        }
        
        if (cbPahaBawah.isSelected())
        {
            int jumlah = Integer.parseInt(txtJumlahPahaBawah.getText());
          
            int harga = PahaBawah * jumlah;
            subtotal += harga;
        }
        
        if (cbSayap.isSelected())
        {
            int jumlah = Integer.parseInt(txtJumlahSayap.getText());
          
            int harga = Sayap * jumlah;
            subtotal += harga;
        }
        
        if (cbAti.isSelected())
        {
            int jumlah = Integer.parseInt(txtJumlahAti.getText());
            
            int harga = Ati * jumlah;
            subtotal += harga;
        }
        
        if (cbPahaAtas.isSelected() && cbPahaBawah.isSelected()) {
            int jumlah1 = Integer.parseInt(txtJumlahPahaBawah.getText());
            int jumlah2 = Integer.parseInt(txtJumlahPahaAtas.getText());
            int jumlah = jumlah1 + jumlah2;
            
            if (jumlah > 5) {
                  potongan = (int) (subtotal*0.05);
            }
        }
        
        if (cbSayap.isSelected() && cbAti.isSelected()) {
            int jumlah1 = Integer.parseInt(txtJumlahAti.getText());
            int jumlah2 = Integer.parseInt(txtJumlahSayap.getText());
            int jumlah = jumlah1 + jumlah2;
            
            if (jumlah > 5) {
                 potongan = (int) (subtotal*0.03);
            }
        }
        
         if (cbPahaAtas.isSelected() && cbPahaBawah.isSelected() && cbSayap.isSelected() && cbAti.isSelected()) {
            int jumlah1 = Integer.parseInt(txtJumlahAti.getText());
            int jumlah2 = Integer.parseInt(txtJumlahSayap.getText());
            int jumlah3 = Integer.parseInt(txtJumlahPahaBawah.getText());
            int jumlah4 = Integer.parseInt(txtJumlahPahaAtas.getText());
            
            int totjum = jumlah1 + jumlah2;
            int totjum1 = jumlah3 + jumlah4;
            if (totjum > 5 && totjum1 > 5) {
                 potongan = (int) (subtotal*0.05) + (int) (subtotal*0.03);
            }
        }
        
        
        if (rbPemesanan.isSelected())
        {
            biayaPesan = (int) (subtotal * 0.05);
        }
        else 
        {
            biayaPesan = 0;
        }
        
        pajak = (int) (subtotal * 0.1);
        totalBayar = subtotal  + biayaPesan + pajak - potongan;
        
        // format pemisah ribuan dan rupiah
        
        // tampilan layar keluaran
       txtOutput.setText("");
       txtOutput.append("Nama Pembeli\t\t"+nama+"\n");
       txtOutput.append("Subtotal\t\tRp."+String.format("%,d", subtotal)+"\n");
       txtOutput.append("Potongan\t\tRp."+String.format("%,d", potongan)+"\n");
       txtOutput.append("Biaya Pesan\t\tRp."+String.format("%,d", biayaPesan)+"\n");
       txtOutput.append("Pajak\t\tRp."+String.format("%,d", pajak)+"\n");
       txtOutput.append("Total Bayar\t\tRp."+String.format("%,d", totalBayar)+"\n");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uts10120205.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uts10120205.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uts10120205.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uts10120205.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uts10120205().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbAti;
    private javax.swing.JCheckBox cbPahaAtas;
    private javax.swing.JCheckBox cbPahaBawah;
    private javax.swing.JCheckBox cbSayap;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbLangsung;
    private javax.swing.JRadioButton rbPemesanan;
    private javax.swing.JTextField txtJumlahAti;
    private javax.swing.JTextField txtJumlahPahaAtas;
    private javax.swing.JTextField txtJumlahPahaBawah;
    private javax.swing.JTextField txtJumlahSayap;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
